# --- Site settings -----------------------------------------------------------
title: Jason Chao Blog
SEOTitle: Jason Chao • Notes on Clinical AI, Bioinformatics & Quant
header-img: img/home-bg.jpg    # make sure this file exists
email:               # change to your public email
description: "這裡是 Jason Chao 的技術筆記，聚焦臨床試驗 AI、單細胞分析與金融量化。"
keyword: "Jason Chao, TrialPathfinder, MIMIC-IV, Bioinformatics, Clinical AI, Quant Trading, Blog"
url: "https://jasonlhc.github.io"       # owner site → keep baseurl empty
baseurl: ""                             # if this is a *project* page use '/repo'

future: true                            # publish future-dated drafts

# --- Social ---------------------------------------------------------------
RSS: true
github_username: JasonLHC
linkedin_username: Jason Chao

# --- Build ---------------------------------------------------------------
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
anchorjs: true
# timezone: Asia/Taipei        # uncomment if date offsets look wrong

plugins:
  - jekyll-paginate

# --- Markdown -------------------------------------------------------------
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1

# --- Comments / Analytics ------------------------------------------------
disqus_username:                       # e.g. jason-blog
ga_track_id: ""                        # e.g. UA-XXXXXX-X
ga_domain: jasonlhc.github.io

# --- Sidebar -------------------------------------------------------------
sidebar: true
sidebar-about-description: |
  AI for clinical trials.  
  Bio- & Fin-informatics explorer.  
  PhD student @ NTU
sidebar-avatar: https://avatars.githubusercontent.com/u/12345678

# --- Tags / PWA ----------------------------------------------------------
featured-tags: true
featured-condition-size: 2
chrome-tab-theme-color: "#ffffff"
service-worker: true

# --- MathJax (optional) --------------------------------------------------
page-mathjax: false

# --- Friends -------------------------------------------------------------
friends:
  - title: "Ebn Zhang"
    href: "https://ebnbin.dev/"
  - title: "Kun Qian"
    href: "http://kunq.me"
